interface Country {
  code: string;
  name: string;
}

export const countries: Country[] = [
  { code: "ar", name: "Argentina" },
  { code: "au", name: "Australia" },
  { code: "at", name: "Austria" },
  { code: "be", name: "Bélgica" },
  { code: "br", name: "Brasil" },
  { code: "ca", name: "Canadá" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cz", name: "República Checa" },
  { code: "dk", name: "Dinamarca" },
  { code: "eg", name: "Egipto" },
  { code: "fi", name: "Finlandia" },
  { code: "fr", name: "Francia" },
  { code: "de", name: "Alemania" },
  { code: "gr", name: "Grecia" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungría" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "ie", name: "Irlanda" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italia" },
  { code: "jp", name: "Japón" },
  { code: "my", name: "Malasia" },
  { code: "mx", name: "México" },
  { code: "nl", name: "Países Bajos" },
  { code: "nz", name: "Nueva Zelanda" },
  { code: "no", name: "Noruega" },
  { code: "ph", name: "Filipinas" },
  { code: "pl", name: "Polonia" },
  { code: "pt", name: "Portugal" },
  { code: "ru", name: "Rusia" },
  { code: "sa", name: "Arabia Saudita" },
  { code: "sg", name: "Singapur" },
  { code: "za", name: "Sudáfrica" },
  { code: "kr", name: "Corea del Sur" },
  { code: "es", name: "España" },
  { code: "se", name: "Suecia" },
  { code: "ch", name: "Suiza" },
  { code: "tw", name: "Taiwán" },
  { code: "th", name: "Tailandia" },
  { code: "tr", name: "Turquía" },
  { code: "ua", name: "Ucrania" },
  { code: "gb", name: "Reino Unido" },
  { code: "us", name: "Estados Unidos" },
  { code: "vn", name: "Vietnam" }
];